### ISSUE TITLE
kites: update to go1.5+

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#8350]
`provider-azure` and `provider-azurerm` depends on go-autorest, which requires go1.5+ (it uses `(*http.Request).Cancel`.

It should be way easier and correct to fix klient log methods and klient/klientctl tests so they work with go1.5+ than to add backward compatibility for 1.4 to azure-go-sdk.

By this issue fix all issues that prevents us from using go1.5+, update wercker-box and wercker.yaml to use go1.5+ version (latest go1.6.2?) and use generated glide.yaml for all vendored files (it is needed in order to flatten dependencies - due to enforced vendor/ rules current kloud code does not build with go1.6 because of:

```
# koding/kites/kloud/stackplan
src/koding/kites/kloud/stackplan/template.go:65: impossible type assertion:
	*"github.com/hashicorp/hcl/hcl/ast".ObjectList does not implement "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".Node (missing "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".node method)
		have "github.com/hashicorp/hcl/hcl/ast".node()
		want "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".node()
src/koding/kites/kloud/stackplan/template.go:106: cannot use obj (type *"github.com/hashicorp/hcl/hcl/ast".ObjectList) as type "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".Node in argument to "github.com/hashicorp/hcl".DecodeObject:
	*"github.com/hashicorp/hcl/hcl/ast".ObjectList does not implement "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".Node (missing "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".node method)
		have "github.com/hashicorp/hcl/hcl/ast".node()
		want "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".node()
src/koding/kites/kloud/stackplan/template.go:216: cannot use t.node.Filter("resource") (type *"github.com/hashicorp/hcl/hcl/ast".ObjectList) as type "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".Node in argument to "github.com/hashicorp/hcl".DecodeObject:
	*"github.com/hashicorp/hcl/hcl/ast".ObjectList does not implement "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".Node (missing "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".node method)
		have "github.com/hashicorp/hcl/hcl/ast".node()
		want "github.com/hashicorp/vendor/github.com/hashicorp/hcl/hcl/ast".node()
```

**Comment by rjeczalik** [comment]
Done.
